# **Tensors and Introduction to Pytorch**

1. **Scalar**

In [ ]:
import torch                           # torch already installed on colab so we only need to import it

In [ ]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [ ]:
scalar.ndim    #  Shows dimension of the tensor

0

In [ ]:
scalar.item()  #  Convert it back into a number

6

**2. Vector**

In [ ]:
vector= torch.tensor([4,2,5])
vector

tensor([4, 2, 5])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

**3. Matrix**

In [ ]:
m= torch.tensor([[2,3],[6,7]])
m

tensor([[2, 3],
        [6, 7]])

In [ ]:
m.ndim

2

In [ ]:
m.shape

torch.Size([2, 2])

**4. 3D Tensor**

In [ ]:
t = torch.tensor([[[1,2],[2,5],[7,8]]])
t

tensor([[[1, 2],
         [2, 5],
         [7, 8]]])

In [ ]:
t.ndim

3

In [ ]:
t.shape

torch.Size([1, 3, 2])

**Generating Random Tensors**

---
Usually used in initiallization of parameters of the model


In [ ]:
# Random 2D tensor
random_tensor= torch.rand(size=(3,4))
random_tensor, random_tensor.shape, random_tensor.dtype

(tensor([[0.7149, 0.9140, 0.0610, 0.5257],
         [0.2197, 0.1849, 0.2594, 0.6817],
         [0.6848, 0.0441, 0.1155, 0.8093]]),
 torch.Size([3, 4]),
 torch.float32)

In [ ]:
random_tensor.ndim

2

In [ ]:
# Random 3D tensor
random_tensor2= torch.rand(size=(224,224,3))
random_tensor2, random_tensor2.shape, random_tensor2.dtype

(tensor([[[0.4953, 0.9313, 0.1950],
          [0.2140, 0.0085, 0.9152],
          [0.6346, 0.5051, 0.3254],
          ...,
          [0.8585, 0.3840, 0.0747],
          [0.4268, 0.4317, 0.1958],
          [0.0598, 0.4124, 0.5563]],
 
         [[0.0879, 0.0012, 0.8746],
          [0.2843, 0.4061, 0.1209],
          [0.9282, 0.3988, 0.6392],
          ...,
          [0.0276, 0.5542, 0.6044],
          [0.9106, 0.3306, 0.6227],
          [0.3817, 0.0252, 0.3017]],
 
         [[0.2725, 0.3863, 0.4373],
          [0.1883, 0.0749, 0.4777],
          [0.8650, 0.2315, 0.1371],
          ...,
          [0.3456, 0.0976, 0.5687],
          [0.3105, 0.5636, 0.8292],
          [0.9368, 0.4550, 0.8403]],
 
         ...,
 
         [[0.4226, 0.7843, 0.8381],
          [0.6575, 0.8032, 0.6670],
          [0.4363, 0.5313, 0.7770],
          ...,
          [0.3906, 0.5234, 0.9182],
          [0.5894, 0.2920, 0.5646],
          [0.6389, 0.9729, 0.0860]],
 
         [[0.9992, 0.0866, 0.5929],
          [0

In [ ]:
random_tensor2.ndim

3

**Generating Tensors of zeros and ones**

In [ ]:
t0=torch.zeros(size=(3,4))
t0, t0.shape, t0.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([3, 4]),
 torch.float32)

In [ ]:
t1=torch.ones(size=(5,6))
t1, t1.shape, t1.dtype

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]),
 torch.Size([5, 6]),
 torch.float32)

# **Tensors filled within a range and Tensor data types**

In [ ]:
t=torch.arange(0,20)
t

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [ ]:
t=torch.arange(start=0, end=20, step=2)
t

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

**Tensor Data types**

In [ ]:
x=torch.tensor([3.0,4.0,2.0],
               dtype=None,
               device=None,
               requires_grad=False)
x, x.dtype,x.shape

(tensor([3., 4., 2.]), torch.float32, torch.Size([3]))

In [ ]:
x=torch.tensor([3.0,4.0,2.0],
               dtype=torch.int64,
               device=None,
               requires_grad=False)
x, x.dtype,x.shape, x.device

(tensor([3, 4, 2]), torch.int64, torch.Size([3]), device(type='cpu'))